version: "3"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: change_me
    command:
      - start-dev
